2024-08-02 01:53:03,237 ::DataConnectionModule-> root - ERROR - ('Error when uploading data: ', NameError("name 'tabl' is not defined"))
2024-08-02 01:54:20,190 - ('Error when uploading data: ', NameError("name 'tabl' is not defined"))
2024-08-02 01:55:19,179 - ERROR - ('Error when uploading data: ', NameError("name 'tabl' is not defined"))
2024-08-02 01:56:02,289 -> ERROR - ('Error when uploading data: ', NameError("name 'tabl' is not defined"))
2024-08-02 01:57:29,200 -> ERROR - (psycopg2.OperationalError) connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-08-02 02:00:41,517 -> ERROR - (psycopg2.OperationalError) connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-08-02 02:03:26,854 -> ERROR - (psycopg2.OperationalError) connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-08-02 02:04:58,347 -> ERROR - (psycopg2.OperationalError) connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-08-02 02:05:34,936 -> ERROR - (psycopg2.OperationalError) connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-08-02 02:11:38,370 -> ERROR - ('Checking connection query failed', OperationalError('(psycopg2.OperationalError) connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"\nconnection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "pedroacastagnola_coderhous"\n'))
2024-08-02 02:12:53,411 -> ERROR - ('Checking connection query failed', SyntaxError('syntax error at or near "."\nLINE 1: SELECT * FROM pedroacastagnola_coderhouse..test;\n                                                  ^\n'))
2024-08-02 02:13:50,719 -> INFO - ('pedro', 'castagnola')
2024-08-02 02:13:50,899 -> ERROR - ('Deleting all data from table failed', SyntaxError('syntax error at or near "."\nLINE 1: DELETE FROM pedroacastagnola_coderhouse..api_tmdb_pelis_terr...\n                                                ^\n'))
2024-08-02 02:14:39,769 -> ERROR - ('Checking connection query failed', TypeError('can only concatenate str (not "tuple") to str'))
2024-08-02 02:16:11,687 -> INFO - Firt row found: ('pedro', 'castagnola')
2024-08-02 02:16:11,868 -> ERROR - ('Deleting all data from table failed', SyntaxError('syntax error at or near "."\nLINE 1: DELETE FROM pedroacastagnola_coderhouse..api_tmdb_pelis_terr...\n                                                ^\n'))
2024-08-02 02:19:14,999 -> INFO - Table doesn't contain any data
2024-08-02 02:19:15,410 -> INFO - Table is now empty
2024-08-02 02:19:15,770 -> INFO - Table doesn't contain any data
2024-08-02 02:19:17,462 -> INFO - Connection closed
2024-08-02 02:20:25,515 -> INFO - Firt row found: ('1010600', 'The Strangers: Chapter 1', 'en', 'After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.', datetime.date(2024, 5, 15), 6.0, 241.0, datetime.datetime(2024, 8, 2, 2, 19, 16, 263455))
2024-08-02 02:20:25,939 -> INFO - Table is now empty
2024-08-02 02:20:26,291 -> INFO - Table doesn't contain any data
2024-08-02 02:20:27,967 -> INFO - New data uploaded!
2024-08-02 02:20:27,968 -> INFO - Connection closed
2024-08-02 02:21:27,756 -> INFO - Firt row found: ('1010600', 'The Strangers: Chapter 1', 'en', 'After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.', datetime.date(2024, 5, 15), 6.0, 241.0, datetime.datetime(2024, 8, 2, 2, 20, 26, 758178))
2024-08-02 02:21:28,180 -> INFO - Table is now empty
2024-08-02 02:21:28,538 -> INFO - Table doesn't contain any data
2024-08-02 02:21:41,181 -> INFO - New data uploaded!
2024-08-02 02:21:41,190 -> INFO - Connection closed
2024-08-02 02:26:41,900 -> INFO - Firt row found: ('1010600', 'The Strangers: Chapter 1', 'en', 'After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.', datetime.date(2024, 5, 15), 6.0, 241.0, datetime.datetime(2024, 8, 2, 2, 21, 34, 369109))
2024-08-02 02:26:42,345 -> INFO - Table is now empty
2024-08-02 02:26:54,161 -> INFO - New data uploaded!
2024-08-02 02:26:54,161 -> INFO - Connection closed
2024-08-02 02:27:34,661 -> INFO - Connecting to database
2024-08-02 02:27:37,820 -> INFO - Firt row found: ('1010600', 'The Strangers: Chapter 1', 'en', 'After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.', datetime.date(2024, 5, 15), 6.0, 241.0, datetime.datetime(2024, 8, 2, 2, 26, 46, 984917))
2024-08-02 02:27:38,266 -> INFO - Table is now empty
2024-08-02 02:27:50,011 -> INFO - New data uploaded!
2024-08-02 02:27:50,011 -> INFO - Connection closed
2024-08-02 02:28:18,822 -> INFO - Connecting to database...
2024-08-02 02:28:21,947 -> INFO - Firt row found: ('1010600', 'The Strangers: Chapter 1', 'en', 'After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.', datetime.date(2024, 5, 15), 6.0, 241.0, datetime.datetime(2024, 8, 2, 2, 27, 42, 834037))
2024-08-02 02:28:22,413 -> INFO - Table is now empty
2024-08-02 02:28:33,968 -> INFO - New data uploaded!
2024-08-02 02:28:33,982 -> INFO - Connection closed
